# Generated by Django 5.0.4 on 2024-05-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0004_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
