# Generated by Django 5.0.4 on 2024-05-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='telegram_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
