# Generated by Django 5.0.4 on 2024-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_api', '0007_task_telegram_id_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='telegram_id',
            field=models.BigIntegerField(),
        ),
    ]
